ODIM-3867 Add tsnotify logic in lib-utilities and use in svc-aggregation
irappa-pattar/ODIM pull request #52
Opened 2020-12-04 09:51 UTC by irappa-pattar

2020-12-04 10:01 UTC, jeevan-kamkar requested changes
Address the changes

2020-12-04 10:01 UTC, jeevan-kamkar commented on svc-aggregation/go.mod
> +replace github.com/ODIM-Project/ODIM/lib-utilities => ../lib-utilities
why this changes required

2020-12-04 10:01 UTC, jeevan-kamkar commented on svc-aggregation/agcommon/common.go
> -	if err != nil {
go mod changes referred with lib utilities don't remove these changes

2020-12-04 11:35 UTC, irappa-pattar commented on svc-aggregation/agcommon/common.go
> -	if err != nil {
addressed

2020-12-04 11:35 UTC, irappa-pattar commented on svc-aggregation/go.mod
> +replace github.com/ODIM-Project/ODIM/lib-utilities => ../lib-utilities
addressed

2020-12-04 11:45 UTC, jeevan-kamkar approved these changes

2020-12-04 11:50 UTC, skhan-anjum approved these changes

2020-12-07 04:39 UTC, a-ajith approved these changes

2020-12-07 05:39 UTC, merged