ODIM-4322 add storage structure in lib-dmtf
irappa-pattar/ODIM pull request #68
Opened 2021-03-15 13:13 UTC by irappa-pattar

2021-03-15 13:24 UTC, jeevan-kamkar approved these changes

2021-03-15 13:28 UTC, amar-shalgar approved these changes
LGTM

2021-03-15 13:34 UTC, bharath-b-hpe approved these changes

2021-03-15 13:59 UTC, shivacharanms approved these changes

2021-03-16 08:33 UTC, Bharath-KKB requested changes
entities like Identifier,  Location and its contained objects - Contacts, PartLocation, Postal, Placement, PostalAddress. Should all belong to a common schema . The common schema shuld also have Common objects
Actions
Capacity
Identifier
IOStatistics
IPv4Address
IPv6Address
IPv6GatewayStaticAddress
IPv6StaticAddress
Location
MaintenanceWindow
Message
OperationApplyTimeSupport
PreferredApplyTime
Redundancy
ReplicaInfo
Schedule
Settings
Status

For now move Identifier,  Location and its contained objects - Contacts, PartLocation, Postal, Placement, PostalAddress to the common schema(lib-dmtf/model/common.go)

2021-03-17 15:02 UTC, Bharath-KKB approved these changes

2021-03-17 15:02 UTC, merged